FROM node:22

RUN apt-get update && apt-get install -y \ 
    chromium \
    libnss3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxcomposite-dev \
    libxdamage1 \
    libxrandr2 \
    libgbm-dev \
    libxkbcommon-x11-0 \
    libasound2

WORKDIR /var/www

COPY ./package-lock.json /var/www
COPY ./package.json /var/www

RUN npm install --omit=dev

